const GET_DOGS = "GET_DOGS",
    GET_DOG_BY_NAME = "GET_DOG_BY_NAME",
    GET_DOG_DETAIL = "GET_DOG_DETAIL",
    GET_TEMPERAMENTS = "GET_TEMPERAMENTS",
    FILTER_TEMPERAMENT = "FILTER_TEMPERAMENT",
    FILTER_FROM = "FILTER_FROM",
    ORDER_BY = "ORDER_BY",
    CREATE_DOG = "CREATE_DOG",
    DELETE_DOG = "DELETE_DOG",
    UPDATE_DOG = "UPDATE_DOG"

module.exports = { GET_DOGS, GET_DOG_BY_NAME, GET_DOG_DETAIL, GET_TEMPERAMENTS, FILTER_TEMPERAMENT, FILTER_FROM, ORDER_BY, CREATE_DOG, DELETE_DOG, UPDATE_DOG }